# Copyright (c) 2023, Grillo del Mal
# 
# Distributed under the 2-Clause BSD License, see LICENSE file.name: Build & Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - run: pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ setuptools_git_versioning cx_Freeze
    - run: pip install -r requirements.txt
    - run: cd src; python freeze.py build_exe

    - name: Archive Zip
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'pytankbattle-windows-x86_64.zip'
        directory: 'out/'
        path: 'src/build/exe.win-amd64-3.12/*'

    - name: 'Release ZIP'
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: 'out/pytankbattle-windows-x86_64.zip'

  macosx-build:
    name: macOSX Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - run: pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ setuptools_git_versioning cx_Freeze
    - run: pip install -r requirements.txt
    - run: cd src; python freeze.py build_exe

    - name: Archive Zip
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'pytankbattle-macosx-x86_64.zip'
        directory: 'out/'
        path: 'src/build/exe.macosx-10.9-universal2-3.12/*'

    - name: 'Release ZIP'
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: 'out/pytankbattle-macosx-x86_64.zip'

  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - run: pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ setuptools_git_versioning cx_Freeze
    - run: pip install -r requirements.txt
    - run: cd src; python freeze.py build_exe

    - name: Archive Zip
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'pytankbattle-linux-x86_64.zip'
        directory: 'out/'
        path: 'src/build/exe.linux-x86_64-3.12/*'

    - name: 'Release ZIP'
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: 'out/pytankbattle-linux-x86_64.zip'
