on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - run: pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze
    - run: pip install -r requirements.txt
    - run: cxfreeze build
    - uses: actions/upload-artifact@v2
      with:
        path: build/*